-- Drop all tables if they exist (in reverse order to avoid FK constraints)
DROP TABLE IF EXISTS BookTags;
DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Reminders;
DROP TABLE IF EXISTS Favorites;
DROP TABLE IF EXISTS UserBooks;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Users;

-- Create Users table (unchanged from Week 1)
CREATE TABLE Users (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(50) NOT NULL UNIQUE,
  Email VARCHAR(100) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  Role ENUM('User', 'Admin') DEFAULT 'User',
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create Books table 
CREATE TABLE Books (
  BookID INT AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(255) NOT NULL,
  Author VARCHAR(100) NOT NULL,
  Type ENUM('Fiction', 'Non-Fiction') NOT NULL,
  Mood VARCHAR(50) DEFAULT NULL,  
  Pace ENUM('Slow', 'Medium', 'Fast') DEFAULT NULL,
  ISBN VARCHAR(13) DEFAULT NULL,
  Summary TEXT DEFAULT NULL,
  CoverURL VARCHAR(255) DEFAULT NULL,
  AddedByUserID INT,
  FOREIGN KEY (AddedByUserID) REFERENCES Users(UserID) ON DELETE SET NULL
);

-- Create UserBooks table 
CREATE TABLE UserBooks (
  UserBookID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  BookID INT NOT NULL,
  ReadingStatus ENUM('Read', 'Reading', 'To Read') NOT NULL,
  Progress INT DEFAULT 0,  -- 0-100 percentage
  DateAdded DATETIME DEFAULT CURRENT_TIMESTAMP,
  Owned BOOLEAN DEFAULT FALSE,
  DNF BOOLEAN DEFAULT FALSE,  
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (BookID) REFERENCES Books(BookID) ON DELETE CASCADE
);

-- Create Favorites table
CREATE TABLE Favorites (
  FavoriteID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  BookID INT NOT NULL,
  DateFavorited DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (BookID) REFERENCES Books(BookID) ON DELETE CASCADE
);

-- Create Reminders table
CREATE TABLE Reminders (
  ReminderID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  BookID INT NOT NULL,
  ReminderDate DATETIME NOT NULL,
  ReminderNote VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (BookID) REFERENCES Books(BookID) ON DELETE CASCADE
);

-- Create Reviews table (with half-star Rating)
CREATE TABLE Reviews (
  ReviewID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  BookID INT NOT NULL,
  ReviewText TEXT DEFAULT NULL,
  Rating DECIMAL(2,1) DEFAULT NULL,  
  DatePosted DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (BookID) REFERENCES Books(BookID) ON DELETE CASCADE
);

-- Create Comments table 
CREATE TABLE Comments (
  CommentID INT AUTO_INCREMENT PRIMARY KEY,
  ReviewID INT NOT NULL,
  UserID INT NOT NULL,
  CommentText TEXT NOT NULL,
  DatePosted DATETIME DEFAULT CURRENT_TIMESTAMP,
  ProgressPercent INT DEFAULT 0,  
  FOREIGN KEY (ReviewID) REFERENCES Reviews(ReviewID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- Create Tags table 
CREATE TABLE Tags (
  TagID INT AUTO_INCREMENT PRIMARY KEY,
  TagName VARCHAR(50) NOT NULL UNIQUE
);

-- Create BookTags junction table 
CREATE TABLE BookTags (
  BookTagID INT AUTO_INCREMENT PRIMARY KEY,
  BookID INT NOT NULL,
  TagID INT NOT NULL,
  FOREIGN KEY (BookID) REFERENCES Books(BookID) ON DELETE CASCADE,
  FOREIGN KEY (TagID) REFERENCES Tags(TagID) ON DELETE CASCADE
);